name: Publish Docs manually

on:
  workflow_dispatch:
    inputs:
      publish_docs:
        default: true
        description: 'Publish docs?' 
      
jobs:       
  release:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.inputs.publish_docs }}
    steps:     
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - name: Deploy documentation
        run: |
          pip install markdown-include
          pip install mkdocs-material==7.2.4
          mkdocs gh-deploy --force