name: Release Modern Search WebParts SPFx package

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'release/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: search-parts

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    
    - name: Build SPFx
      run: |
        pnpm install
        gulp update-version --value $GITVERSION_MAJORMINORPATCH
        gulp update-package-name --name pnp-modern-search-parts-$GITVERSION_SEMVER
        gulp bundle --ship
        gulp package-solution --ship

    - name: Create GitHub release
      uses: ncipollo/release-action@v1
      with:
        name: PnP Modern Search - ${{ steps.gitversion.outputs.majorMinorPatch }}
        artifacts: ${{ github.workspace }}/**/*.sppkg
        bodyFile: ".github/workflows/release-template.md"
        draft: true
        generateReleaseNotes: true
        allowUpdates: true
        replacesArtifacts: true
        prerelease: ${{ startsWith(github.ref_name, 'release') }}
        tag: ${{ steps.gitversion.outputs.majorMinorPatch }}
        commit: ${{ github.ref_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pnp-modern-search-parts-${{ steps.gitversion.outputs.semVer }}
        path: ${{ github.workspace }}/**/*.sppkg
